[workspace]
members = [
    "compiler/workspaces/runec",
    "compiler/workspaces/runec_utils",
    "compiler/workspaces/runec_errors",
    "compiler/workspaces/runec_parse",
    "compiler/workspaces/runec_source",
    "compiler/workspaces/runec_fluent_messages"
]
resolver = "3"
